<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("header-class", "header_transparent top");
?>

<?$APPLICATION->IncludeComponent(
    "bitrix:news",
    "lizing",
    Array(
        "DETAIL_SET_BROWSER_TITLE" => "Y",
        "LIST_SET_BROWSER_TITLE" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_META_DESCRIPTION" => "Y",
        "LANGUAGE_ID" => mb_strtoupper(LANGUAGE_ID),
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_SHADOW" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => CACHE_FILTER,
        "CACHE_GROUPS" => CACHE_GROUPS,
        "CACHE_TIME" => CACHE_TIME,
        "CACHE_TYPE" => CACHE_TYPE,
        "CHECK_DATES" => "Y",
        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_FIELD_CODE" => array("",""),
        "DETAIL_PAGER_SHOW_ALL" => "N",
        "DETAIL_PAGER_TEMPLATE" => "",
        "DETAIL_PAGER_TITLE" => "Лизинг",
        "DETAIL_PROPERTY_CODE" => array("DETAIL_TITLE", "TOP_DESCRIPTION", "TITLE_DETAIL_TEXT", "TITLE_LIST", "LIST", "AFTER_LIST_TEXT", "BASIC_REQUIREMENT", "SHOW_QUESTIONS_BANNER", "HTML_AFTER_BANNER", "LAST_BLOCK_DESCRIPTION","DOCUMENTS","DETAIL_SUBTITLE"),
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PANEL" => "N",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "HIDE_LINK_WHEN_NO_DETAIL" => "Y",
        "IBLOCK_ID" => LIZING_IBLOCK_ID,
        "IBLOCK_TYPE" => CONTENT_IBLOCK_TYPE,
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "LIST_FIELD_CODE" => array("",""),
        "LIST_PROPERTY_CODE" => array(""),
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "NEWS_COUNT" => UNLIMITED_COUNT,
        "NUM_DAYS" => "30",
        "NUM_NEWS" => "20",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => CACHE_TIME,
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "",
        "PAGER_TITLE" => "Проекты",
        "PREVIEW_TRUNCATE_LEN" => "",
        "SEF_FOLDER" => "/",
        "SEF_MODE" => "Y",
        "SEF_URL_TEMPLATES" => Array(
            "detail"=>"#ELEMENT_CODE#/",
            "news"=>"",
            "section"=>"",
        ),
        "SET_LAST_MODIFIED" => "N",
        "SET_TITLE" => "Y",
        "SORT_BY1" => "SORT",
        "SORT_BY2" => "ACTIVE_FROM",
        "SORT_ORDER1" => "ASC",
        "SORT_ORDER2" => "DESC",
        "STRICT_SECTION_CHECK" => "N",
        "USE_CATEGORIES" => "N",
        "USE_FILTER" => "N",
        "MAIN_FILTER_NAME" => "",
        "USE_PERMISSIONS" => "N",
        "USE_RATING" => "N",
        "USE_REVIEW" => "N",
        "USE_RSS" => "N",
        "USE_SEARCH" => "Y",
        "USE_SHARE" => "N",
        "YANDEX" => "N",
        "SHARE_HANDLERS" => array("facebook","vk","twitter"),
        "SHARE_HIDE" => "N",
        "SHARE_SHORTEN_URL_KEY" => "",
        "SHARE_SHORTEN_URL_LOGIN" => "",
        "SHARE_TEMPLATE" => "",
        "SET_STATUS_404" => "Y",
        "SHOW_404" => "Y",
        "MESSAGE_404" => "",
        "LIST_NEWS_COUNT" => UNLIMITED_COUNT,
    )
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>