<?
$GLOBALS[MAIN_SHOW_FILTER_NAME] = ['!PROPERTY_MAIN_SHOW' => false,];
$GLOBALS[BANNER_INVESTOR_FIRST_FILTER_NAME] = ['PROPERTY_TYPE' => 11,];
$GLOBALS[BANNER_INVESTOR_SECOND_FILTER_NAME] = ['PROPERTY_TYPE' => 12,];
$GLOBALS[BANNER_INVESTOR_THIRD_FILTER_NAME] = ['PROPERTY_TYPE' => 13,];
$GLOBALS[BANNER_SALE_FILTER_NAME] = ['PROPERTY_TYPE' => 14,];
$GLOBALS[BANNER_HEADER_FILTER_NAME] = ['PROPERTY_TYPE' => 16,];
$GLOBALS[BANNER_MENU_SIDEBAR_FILTER_NAME] = ['PROPERTY_TYPE' => 17,];